### ISSUE TITLE
Unexpected token '??='

### ISSUE THREAD

**Issue by hurui79** [ForkFG/TerminalXbqg#14]
```
if (! flag.interactive) cmd_n ??= "help"
                                              ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:4
```

如何用npm命令运行

**Comment by ForkKILLET** [comment]
@390029659 fixed

npm 运行暂不支持，可能会加入。
直接 `./main.js` 可以运行，建议把 `/path/to/main.js` 扔到 path 里（我自己是这么用的）

谢谢反馈！

**Comment by ForkKILLET** [comment]
`SyntaxError: Unexpected token '??='` 可能的原因：您的 node 版本过低？
